dist: xenial
language: ruby
rvm:
  - 2.5.0
sudo: true
before_install:
  - gem update --system
  - gem install bundler -v 1.17.2
script:
  - bundle exec rspec spec && gem build clean_rm.gemspec && gem install clean_rm*gem
