#!/usr/bin/env ruby
#
require 'clean_rm'
require 'clean_rm/cli'

$script_name = File.basename(__FILE__)
$err_status  = 0

cli = CleanRm::CLI.new()

filenames = cli.parse_opts(ARGV)
request = cli.option

CleanRm::Trashcan.new(:Console) do |trash|

  # NB: Order is critical here!
  #     `trash -lR' recursively lists,
  #     `trash -R'  recursively removes.
  if request[:list]
    trash.list(filenames, request)
  elsif request[:empty]
    trash.empty(filenames, request)
  elsif filenames.empty?
    cli.parse_opts(%w[--help])
  elsif request[:whiteout]
    trash.restore(filenames, request)
  else
    trash.transfer(filenames, request)
  end
end

exit $err_status
